LivePersonInc/developer-center

pages/documents/consumer experience/CoAppAndroid-sdk/Customizing/Appearance-&-Behavior.md
pages/documents/consumer experience/CoAppAndroid-sdk/FAQ.md
pages/documents/consumer experience/CoAppAndroid-sdk/Getting Started/Integrate-SDK.md
pages/documents/consumer experience/CoAppAndroid-sdk/Getting Started/Integration-Guide.md
pages/documents/consumer experience/CoAppAndroid-sdk/Getting Started/Prerequisites.md
pages/documents/consumer experience/CoAppAndroid-sdk/LiveEngage Configuration/Account-Settings.md
pages/documents/consumer experience/CoAppAndroid-sdk/Sample-Apps.md
pages/documents/consumer experience/CoAppiOS-sdk/Customizing/Appearance-&-Behavior.md
pages/documents/consumer experience/CoAppiOS-sdk/Customizing/Wording.md
pages/documents/consumer experience/CoAppiOS-sdk/Getting Started/Integrate-SDK-Manually.md
pages/documents/consumer experience/CoAppiOS-sdk/Getting Started/Integrate-SDK-using-CocoaPods.md
pages/documents/consumer experience/CoAppiOS-sdk/Getting Started/Integration-Guide.md
pages/documents/consumer experience/CoAppiOS-sdk/Getting Started/Prerequisites.md
pages/documents/consumer experience/CoAppiOS-sdk/Getting Started/Project-Settings.md
pages/documents/consumer experience/CoAppiOS-sdk/Introduction.md
pages/documents/consumer experience/CoAppiOS-sdk/LiveEngage/Account-Settings.md
pages/documents/consumer experience/CoAppiOS-sdk/LiveEngage/VoIP-Configuration.md
pages/documents/consumer experience/CoAppiOS-sdk/Sample-Apps.md

We fixed many styling issues and aligned the content of both SDK docs. Tested locally using Jekyll.

fixed styling issues and adjusted content for CoApp iOS & Android

---

assets/content/ServerChatAPI.postman_collection

Reverts LivePersonInc/developers-community#12

Revert "Update ServerChatAPI.postman_collection"

---

pages/documents/consumer experience/android-sdk/methods/methods.md

typo in documentation for method handlePushMessage

Update methods.md - handlePushMessage

---

pages/documents/consumer experience/android-sdk/photo-sharing.md
pages/documents/consumer experience/ios-sdk/Methods/messaging methods.md
pages/documents/consumer experience/ios-sdk/quick-start.md
pages/documents/consumer experience/ios-sdk/toastnotifications.md

Note for Photo Sharing on SDK 3.0, this feature needs to add Notification Channel support when using SDK 3.0 on Oreo Devices

PhotoSharing Note

---

pages/documents/consumer experience/ios-sdk/Methods/messaging methods.md

Notes added to the RegisterForPushNotifications, Initialize and Logout methods.

iOS SDK Notes

---

pages/documents/consumer experience/ios-sdk/Methods/messaging methods.md

Fix iOS RegisterForPush Styling

Fix styling issue on iOS Documentation

---

pages/documents/RealTimeData/AgentMetricsAPI/Methods/Agent Status.md

Please add timestamp, which I was given by R&D as a solution for something I was working on.
Adding this to the documentation in order to ensure what we are being given by R&D is documented and supported going forward.

Update Agent Status.md

---

_data/reportbuilder.yaml

Added new metrics released in March (response time metrics - RB 3.1)

New metrics added (RB3.1)

---

pages/documents/ClientSideConfiguration/FaaS/getting-started.md

- Added notice with a description of the currently supported browsers

:globe_with_meridians: Modified FaaS docs

---

pages/documents/ClientSideConfiguration/FaaS/overview.md

Signed-off-by: Simon Pelczer <spelczer@liveperson.com>

Linked the freshly created waiting list form

---

pages/documents/DeveloperTools/FaaS/Developing/toolbelt.md

Extended the existing documentation to also include the new SMTP Client and also Sample Usage.
Signed-off-by: Simon Pelczer <spelczer@liveperson.com>

Extended Documentation to include Email Client

---

pages/documents/DeveloperTools/FaaS/Developing/event-templates.md

Signed-off-by: Simon Pelczer <spelczer@liveperson.com>

Added Email Template to the list of templates

---

pages/documents/AgentExperience/ChatAgentAPI/Methods/retrieve-agent-information.md

Request method contains additional `api/account/{accountId}` which is incorrect

Fix request method for retrieve agent info

---

pages/documents/DeveloperTools/FaaS/use-cases/post-chat-survey-with-faas.md

Wrong var names in FaaS example

---

_data/documentsupdated.yaml
pages/documents/AgentExperienceAndBots/ConversationBuilder/BestPractices/Tips_and_Tricks_v2.2.md
pages/documents/DeveloperTools/FaaS/External Invocations/authorization-code.md
pages/documents/DeveloperTools/FaaS/External Invocations/client-credentials.md
pages/documents/DeveloperTools/FaaS/External Invocations/overview.md

Reverts LivePersonInc/developers-community#326. Feature was delayed.

Revert "Staging"

---

pages/documents/ClientSideConfiguration/JavaScriptChatSDK/Methods/setvisitorname.md

Fix javascript property for context

Minor fix in setVisitorName page

---

pages/documents/ClientSideConfiguration/EngagementWindowWidgetSDK/how-to-use/code-examples.md

var content =  eventData.data.content = ""; cause every message to be empty

Fix empty messages

---

pages/documents/DeveloperTools/FaaS/Developing/event-templates.md

@EdenKupe let me know if LE UI is the correct wording

Based on feedback clarified a bit

---

pages/documents/DeveloperTools/FaaS/Developing/toolbelt.md

JSON response is more popular and change the full response to false to only get the body back.
This will be a better example to grab and try

Adjusting the example to be with JSON=true

---

pages/documents/BotsAndAutomation/Maven/aiPoweredRouting/intentAndContextPolicies.md
pages/documents/BotsAndAutomation/Maven/aiPoweredRouting/setupInLivePerson.md

Fix broken img link on https://developers.liveperson.com/maven-ai-powered-routing-intent-context-policies.html. Fixes #384

Fix broken img link.

---

_layouts/register.html
js/register.js

- Added basic email validation to the static web form. Error handling in case of server errors should be improved further
- Replaced arrow function with standard function declaration for browser compatibility

Rapiddeploy webform emailcheck

---

js/register.js

Update registration form to new URL

---

_includes/registerHead.html

Validated registration working at localhost via Hotjar ui.

add hotjar tracking code to registerHead template

---

_layouts/register.html
js/register.js

* Expanded regex to match permitted special characters described in html
* Added more specific validation error messages

add matches to regex to correspond to hint, add more validation error messages

---

js/register.js

See https://help.hotjar.com/hc/en-us/articles/115011576827-Understanding-the-Form-Report

add hotjar registration form success and failure calls

---

pages/documents/DeveloperTools/FaaS/getting-started.md

- Changed it to reflect the status quo of provisioning

Changed provisioning disclaimer

---

pages/documents/DeveloperTools/FaaS/Integrations/conversational-commands.md

Conversational Commands

---

pages/documents/DeveloperTools/FaaS/Developing/toolbelt.md
pages/documents/DeveloperTools/FaaS/Developing/whitelisting.md

:pencil: updated FaaS-LpClient/ Whitelisting documentation -mschabel

---

pages/documents/DeveloperTools/FaaS/getting-started.md

Please merge to production ASAP, thanks.

:pencil: changing structure of docs

---

pages/documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ConfiguringtheSDK/attributes.md

Reverts LivePersonInc/developers-community#474

Revert "Sdk attr"

---

pages/documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ConfiguringtheSDK/attributes.md

Reverts LivePersonInc/developers-community#475

Revert "Revert "Sdk attr""

---

pages/documents/MessagingChannels/PushNotificationService/configuration.md

Push proxy is now configured by the brand in LE Console
reference: https://knowledge.liveperson.com/release-notes-2018-october-week-of-october-15th.html#push-notification-proxy---self-service-le-89348

Update push proxy configuration page

---

pages/documents/MessagingChannels/ConnectorAPI/api-reference/api-overview.md

Correct spelling mistake

---

_includes/head.html
_includes/registerHead.html

This reverts commit 7846138ac4576800115a56f74b0f9cd900f9b535.

Revert "Add additional scripts to resolve cookies."

---

pages/documents/DeveloperTools/FaaS/Integrations/faas-for-messaging.md

This PR contains the information for the transfer to agent feature in FaaS. Can be merged directly.

feature/FS-312: Transfer to agent

---

pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/interface-and-class-definitions.md

* update interface-and-class-definition with latest API in the SDK

update interface-and-class-definition with latest API in the SDK

---

_data/documentsupdated.yaml
_layouts/register.html
pages/documents/SecurityAndAuthenication/MobileSDKAndWebAuthentication/howitworks.md
pages/documents/SecurityAndAuthenication/MobileSDKAndWebAuthentication/majorcomponents.md

Change site key for registration page

Hotfix registration 2020 01 20

---

_includes/sidebar.html

Adding the registration button back in at Jason's suggestion.
This reverts commit dae94b1a6fa001e1564d109300fd0d8845d84cb0.

Revert "Comment out free trial button."

---

pages/documents/DeveloperTools/FaaS/Developing/storing-secrets.md

* Adjusted Note section to be similiar to what is used in event section
* Shorten User Permission description
* Shorten Notes
* Moved block text before notice

:pencil: Multiple Adjustments

---

pages/documents/ClientSideConfiguration/MessagingWindowAPI/tutorials/cobrowse.md

Removes site setting coapp enabled from prerequisites

---

pages/documents/RichMessaging/QuickReplies/Quick-Replies-Facebook.md

This PR updates the number of quick replies for the Facebook messenger template

Changes amount of quick replies for facebook messenger template

---

pages/documents/ConversationalAI/MessagingAgentSDK/Conversation Metadata Guide.md

in UMS there is a limit to number of intents - 16. Need to specify it not to cause the confusion.

Specify the number of intents ( limited by the Json schema )

---

js/register.js

Reverts LivePersonInc/developers-community#557

Revert "Revert "Revert "Revert "Revert "Use new free-trial-backend at self-se…"

---

pages/documents/ConversationalAI/ConversationBuilder/ScriptingFunctions/getIntegrationData.md

param needs to be path in object not an object itself

param needs to be path in object not object itself

---

js/register2.js

Reverts LivePersonInc/developers-community#578

Revert "Change URL for registration backend to self-service.liveperson.com/ap…"

---

js/register2.js

Reverts LivePersonInc/developers-community#579

Revert "Revert "Change URL for registration backend to self-service.liveperson.com/ap…""

---

_layouts/register2.html
js/register2.js

Add special message for if the user doesn't use an approved buisness

---

css/default.css
css/inner-page.css

fixed navbar height and padding

fixed navbar height

---

pages/index.md

Trying to get image to load

---

_layouts/confirmation.html

Updated confirmation logo to match the welcome logo

Confirmation logo

---

pages/documents/GettingStarted/do-more-with-conversation-cloud.md

second getting started link has a broken url

changed url so wont redirect

---

_data/releasenotesios.yaml
pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/ReleaseNotes/additional/5.2.1.md
pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/ReleaseNotes/allreleases.md

Release notes for iOS SDK 5.2.1

Additional Release - iOS SDK 5.2.1

---

pages/documents/ClientSideConfiguration/MessagingWindowAPI/APIReference/overview.md
pages/documents/GettingStarted/Retry Policy Recommendation.md
pages/documents/RealTimeData/MessagingOperationsAPI/methods/messaging-conversation.md
pages/documents/RealTimeData/MessagingOperationsAPI/methods/messaging-csat-distribution.md
pages/documents/RealTimeData/MessagingOperationsAPI/methods/messaging-current-queue-health.md
pages/documents/RealTimeData/MessagingOperationsAPI/methods/messaging-queue-health-by-group.md
pages/documents/RealTimeData/MessagingOperationsAPI/methods/messaging-queue-health.md
pages/documents/RealTimeData/OperationalRealtimeAPI/methods/agent-activity.md
pages/documents/RealTimeData/OperationalRealtimeAPI/methods/current-queue-state.md
pages/documents/RealTimeData/OperationalRealtimeAPI/methods/engagement-activity.md
pages/documents/RealTimeData/OperationalRealtimeAPI/methods/queue-health.md
pages/documents/RealTimeData/OperationalRealtimeAPI/methods/sla-histogram.md

Includes some verbiage updates regarding UMS retry policies as they relate to rate-limiting / 429 response codes.

Update rate-limiting policies.

---

README.md
pages/documents/DeveloperTools/FaaS/Integrations/messaging-survey.md
web-messaging/emulator.html

Reverts LivePersonInc/developers-community#855

Revert "Feature/merge master"

---

web-messaging/css/ftue.css
web-messaging/emulator.html
web-messaging/intro.html

Removed unused outdated modals and the clipboard js script. Updated talk to your concierge bot in web emulator FTUE to Message with your Concierge Bot. Updated spotlight to be visible on small screens

removed the unused modals and clipboard

---

css/default.css

anchor list height was shortened so added a scrollbar

added scroll bar to the anchor list

---

pages/Documents/Security&Authentication/MTLS/creating-a-p12-file.md

Recreated the creating p12 file

Adding creating p12 file

---

pages/Documents/Security&Authentication/AuthorizingConversationalCloudApplications/Methods/token-revocation-request.md

Fix 404 in revocation API page

Fix 404 in revocation API page

---

pages/Documents/ConversationalAI/ConversationBuilder/ScriptingFunctions/functions-list.md
pages/Documents/ConversationalAI/ConversationBuilder/ScriptingFunctions/get-set-contextual-data.md

Add missing args to getLPEngagementAttribute scripting function

Add missing args to getLPEngagementAttribute scripting function

---

pages/Documents/ConversationalAI/ConversationBuilder/Dialogs/dialog-basics.md

Fix bug in Import Dialog procedure

Fix bug in Import Dialog procedure

---

pages/Documents/ConversationalAI/BotAnalytics/overview.md
pages/Documents/ConversationalAI/BotsStatus/overview.md
pages/Documents/ConversationalAI/ConversationBuilder/Tutorials&Guides/getting-started.md
pages/Documents/ConversationalAI/ConversationOrchestrator/overview.md
pages/Documents/ConversationalAI/ConversationalAI/overview.md
pages/Documents/ConversationalAI/IntentAnalyzer/overview.md
pages/Documents/ConversationalAI/IntentBuilder/overview.md
pages/Documents/ConversationalAI/KnowledgeBase/overview.md

Add banner note about AI forum

Add banner note about AI forum

---

pages/Documents/ConversationalAI/BotAccounts/credentials.md

Update doc on adding a Mutual Authentication credential

Update doc on adding a Mutual Authentication credential

---

_data/releasenotesios.yaml
pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/QuickStarts/quick-start-6-0-and-up-xcframework-support.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/ReleaseNotes/Additional/5.2.2.md

* 5.2.2 release note
* some update on the quick start

5.2.2 release note and some update on the quick start

---

pages/Documents/ConversationalAI/ConversationBuilder/ScriptingFunctions/get-user-data.md

Update description for getUserPlatformId CB scripting function

Update description for getUserPlatformId CB scripting function

---

pages/Documents/ClientSideConfiguration/WindowCustomizationAPI/quick-start.md

Added CSS rules for overriding border styles for maximized and minimized window

[CAO-19136] Updated Window Customization API

---

pages/Documents/ConversationalAI/ConversationBuilder/variables-slots.md
pages/Documents/ConversationalAI/KnowledgeBase/ExternalKnowledgeBases/introduction.md
pages/Documents/ConversationalAI/Tutorials&Guides/BotGroups&OtherTechniques/overview.md
pages/Documents/ConversationalAI/Tutorials&Guides/GettingStartedWithBotBuilding/overview.md

Fix bad redirect link and integrate copy edits

Fix bad redirect link and integrate copy edits

---

_data/documentsupdated.yaml
pages/Documents/GettingStarted/APIGuidelines/important-updates.md

Update ferreira branch with master branch

Update ferreira branch with master branch

---

pages/Documents/ConversationalAI/Tutorials&Guides/BotGroups&OtherTechniques/bot-groups-collaboration.md

Reorder steps in adv tutorial step 3 - This is necessary to avoid hitting a dev bug.

Reorder steps in adv tutorial step 3

---

pages/Documents/ConversationalAI/Tutorials&Guides/BotGroups&OtherTechniques/bot-groups-collaboration.md

Add video to Bot Groups advanced CB tutorial

Add video to Bot Groups advanced CB tutorial

---

pages/Documents/ConversationalAI/IntentBuilder/overview.md

Fix dead link to Intent Builder Overview page

Fix dead link to Intent Builder Overview page

---

pages/Documents/Security&Authentication/ConsumerAuthentication/major-components.md

Auth header is Authorization with basic base64 encoded ClientId:ClientSecret

Auth header is wrong

---

pages/Documents/ConversationalAI/ConversationBuilder/Bots/post-conversation-survey-bots.md

Add note that only English-language survey bots are supported

Add note that only English-language survey bots are supported

---

pages/Documents/Hidden/Hidden/meaningful-automation-conversation-score.md

Add draft MACS content

---

pages/Documents/Hidden/Hidden/meaningful-automation-conversation-score.md

Update data on accuracy of MACS

Update data on accuracy of MACS

---

pages/Documents/ConversationalAI/ConversationBuilder/ScriptingFunctions/manage-the-conversation-context-service.md

add helper function to Get All Variables section in Manage the Conversation Context Service topic

add helper function to Get All Variables section in Manage the Conversation Context Service topic

---

pages/Documents/Hidden/Hidden/meaningful-automation-conversation-score.md

Update MACS descriptors

---

_layouts/hidden-post.html

Created a layout for hidden posts as hidden-layout is not able to use the post layout

attempting to add the post layout for hidden layout

---

_layouts/hidden-layout.html

fix for last push of post content being added to hidden layout

adding only necessary content

---

pages/Documents/Hidden/Hidden/meaningful-automation-conversation-score.md

Add note about MACS for closed convs

Add note about MACS for closed convs

---

pages/Documents/Hidden/Hidden/meaningful-automation-conversation-score.md

Update MACS score descriptors

---

pages/Documents/Hidden/Hidden/meaningful-automation-conversation-score.md

add video URL

---

pages/documents/HistoricalData/EngagementHistoryAPI/methods/retrieve-engagement-list-by-criteria.md

add prediction label

---

pages/documents/HistoricalData/EngagementHistoryAPI/methods/retrieve-engagement-list-by-criteria.md

Add intent for chat

---

pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/QuickStarts/quick-start-5-2-1-and-below.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/QuickStarts/quick-start-6-0-and-up-xcframework-support.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/ReleaseNotes/Additional/5.2.1.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/Resources/faq.md

- faq.md: Adding new FAQ for Blank Bubbles
- QuickStarts:
- Fixing markup,
- Fixing logic for removingConversation

iOS SDK Updates

---

_config.yml

updated the config to add codes to index

Adding code to algolia nodes to index

---

package-lock.json
package.json

Update axios vulnerability

---

_config.yml

Adding back in other nodes_to_index and included td

---

pages/Documents/ConversationalAI/IntentBuilder/overview.md

Following guidance from https://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown

Bookmark for domains_definition

---

package-lock.json
package.json

Addressed all moderate to high severity issues with package.json . This has been tested in the staging branch

updated the package to address security issues.

---

pages/Documents/MessagingChannels/ConnectToMessaging/api.md

Update on the merged pr: https://github.com/LivePersonInc/developers-community/pull/1114

Update c2m doc

---

pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/Resources/faq.md

- Adding FAQ note on VoiceOver Assistant regarding Accessibility.

iOSSDK FAQ VoiceOver

---

pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/QuickStarts/quick-start-5-2-1-and-below.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/QuickStarts/quick-start-6-0-and-up-xcframework-support.md

- Adding section for Accessibility on Quick Start guides, showcasing how to handle VO, while using WindowMode.

iOSSDK QuickStart Accessibility

---

pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/AdvancedFeatures/voice-and-video.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/4.8.1.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/5.6.0.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/releasenotes.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/push-notifications.md

Update features and permissions elements requirements.

Update Release Notes for Android Messaging SDK v4.8.1 and v5.6.0

---

pages/Documents/GettingStarted/APIGuidelines/domain-api.md

Don't suggest that users should persist any results from Domain API

Remove mention of using static results of Domain API.

---

pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/ReleaseNotes/Regular/6.5.0.md

Adding note stating UMS version required for DatePicker

iOS SDK 6.5.0

---

pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/4.9.0.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/5.7.0.md
pages/Documents/RichMessaging/MobileSDKandWebTemplates/date-picker-template.md

- Adding note to JSON Schema and Android Release Notes stating support for UMS version.

MobileSDK UMS DatePicker Dependency

---

pages/Documents/ConversationalAI/ConversationBuilder/Testing&Deployment/deploying-to-conversational-cloud.md

Enhance the doc on the defaultGreetingMessage field
Add doc on the disableGreetings field

Update doc on CB custom configuration fields for agent connectors

---

pages/Documents/MessagingChannels/ConnectToMessaging/api.md

https://jira.liveperson.com/browse/LIVX-2513

Update SDE's phone number for C2M API

---

_data/documentsupdated.yaml
pages/Documents/MessagingChannels/PushNotificationService/Configuration/apple-token-authentication.md
pages/Documents/MessagingChannels/PushNotificationService/Configuration/push-proxy.md

Pusher Service

---

pages/Documents/MessagingChannels/ConnectorAPI/SendAPI/authorization-and-authentication.md
pages/Documents/Security&Authentication/ConsumerAuthentication/detailed-api.md

fix iss value

---

_data/releasenotesandroid.yaml
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/5.7.0.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/5.7.1.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/releasenotes.md

Android SDK release notes for 5.7.1

Android SDK release notes for 5.7.1

---

pages/Documents/Reporting/DataAccessAPI/overview.md

The link to data APIs information was broken.

Updated the link in Introduction to the correct one

---

package-lock.json

removed artifactory

---

_data/apimetrics.yaml
_data/reportbuilder.yaml
_exclude/CustomerFacingBots/getstarted.md
_exclude/nlu-engines-troubleshooting.md
assets/Code examples/APIs/Engagement History API/README.md
pages/Documents/Solutions/CustomerFacingBots/getting-started.md
pages/Solutions/CustomerFacingBots/getting-started.md

(and fix some spellings of “Node.js”)

docs: add missing spaces

---

pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/SDKAPIs/monitoring-api.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/SDKAPIs/monitoring-api.md

- Adding footnote stating optional parameter becomes required in certain scenarios.

MobileSDK MonitoringAPI

---

pages/Documents/MessagingChannels/ConnectToMessaging/api.md

The c2m wiki needs to be updated to have multiple SMS variables. This PR will generate the desired changes.
References -  https://jira.liveperson.com/browse/LIVX-2683

updating wiki for multiple SMS variables

---

pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/ReleaseNotes/Regular/6.6.0.md

iOS SDK 6.6.0

---

_data/documentsupdated.yaml
pages/Documents/ClientSideConfiguration/MessagingWindowAPI/Tutorials/legacy-post-conversation-survey-pcs.md

Reverts LivePersonInc/developers-community#1518
@lp-cilkiw the link is broken and is an infinite redirect, rolling back

Revert "Remove legacy references in PCS documentation"

---

pages/Documents/ConversationalAI/Third-PartyBots/CustomEndpoint/introduction.md
pages/Documents/ConversationalAI/Third-PartyBots/LivePersonFunctions/advanced-features.md
pages/Documents/ConversationalAI/Third-PartyBots/LivePersonFunctions/basic-content.md
pages/Documents/ConversationalAI/Third-PartyBots/LivePersonFunctions/introduction.md
pages/Documents/ConversationalAI/Third-PartyBots/bot-conversation-errors.md
pages/Documents/ConversationalAI/Third-PartyBots/conversation-tester.md

- Fixed the Links of LivePerson Functions in the conversation tester page
- Updated Conversation Error list 
- Updated disclaimer notice of the custom endpoint page
- Updated LivePerson Function documentation link for Getting Started

🔧 (INT-2193) TPB Documentation Update

---

pages/Documents/DeveloperTools/LivePersonFunctions/ToolbeltDocumentation/toolbelt.md

Adding context service whitelisting information

:FC-1236: :memo: context service whitelisting information

---

pages/Documents/ContactCenterManagement/ShiftStatusAPI/overview.md

Updating jwt call details as it is not documented anywhere

updating shift status by skill for retrieving JWT

---

pages/Documents/ContactCenterManagement/UsersAPI/Methods/delete-user.md
pages/Documents/ContactCenterManagement/UsersAPI/Methods/delete-users.md

Update users delete api document

Update users delete api document

---

pages/Documents/MessagingChannels/AppleBusinessChatSDK/overview.md

Simple spelling/grammar fixes to AppleBusinessChatSDK/overview.md

AppleBusinessChatSDK/overview.md spelling/grammar adjustments

---

_data/releasenotesios.yaml
pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/ReleaseNotes/Limited/6.8.3.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforiOS/StringLocalization/localization-keys.md

- Adding release notes for iOS SDK 6.8.3 Limited Release

iOS SDK 6.8.3

---

README.md

docs: add extra installation pointer, and improve formatting and punctuation

---

_data/documentsupdated.yaml
pages/Documents/ConversationalAI/ConversationBuilder/Bots/post-conversation-survey-bots.md
pages/Documents/ConversationalAI/ConversationBuilder/bot-examples-more.md

This CB doc update:
- Fixes issue https://github.com/LivePersonInc/developers-community/issues/1041 by updating the FAQ in question
- Adds a "Bot Examples & More" topic that links to our CB GitHub repo that contains bot examples, sample code, etc.

Conversation Builder doc updates 

---

.platform/routes.yaml

chore: add free trial redirect (and extend redirect expiration)

---

README.md

(and moved “Hiding files” section)

Added (initial) style guide

---

pages/Documents/ConversationalAI/ConversationBuilder/ScriptingFunctions/send-messages.md

fix: correct link destination

---

_includes/google_analytics.html
_layouts/bot-integration.html
_layouts/confirmation.html
_layouts/default.html
_layouts/developing-chat.html
_layouts/documents.html
_layouts/events.html
_layouts/homepage.html
_layouts/messaging-api-sdk.html
_layouts/register.html
_layouts/search.html
_layouts/solutions.html
_layouts/summit.html

refactor: improve HTML code

---

README.md

docs: complement, clean up, and restructure installation section

---

_includes/head.html
_includes/registerHead.html
_layouts/register.html
css/default.css
css/inner-page.css

As per DX-76, the solution clamps the image size (which gets the TOC to show consistently), and then hides the TOC in small viewports.

Improved TOC styling (and minor improvements)

---

pages/Documents/MessagingChannels/ConnectToMessaging/api.md

Updated Connect to messaging with Google RCS channel

C2m grcs updates dev wiki

---

css/default.css
css/inner-page.css
css/inner-page.min.css

Improved breaking behavior in tables

---

_layouts/default.html
_layouts/hidden-layout.html
config/schedule.rb
package-lock.json
package.json
pages/Documents/APIGuidelines/oauth-2-0-client-credentials.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/quick-start.md
pages/Documents/Reporting/EngagementHistoryAPI/sample-code.md
pages/Documents/Solutions/Transporter/creating-report-tasks.md
pages/Solutions/Transporter/creating-report-tasks.md

feat: adjust to repository name change (“developer-center”)

---

_layouts/default.html
css/default.css

[DX-101](https://jira.liveperson.com/browse/DX-101)

fixed hamburger focus

---

assets/code-examples/WebAppSDK/TieredResponsesWidget/README.md
pages/Documents/ContactCenterManagement/PredefinedCategoriesAPI/Methods/import-account-categories.md
pages/Documents/ContactCenterManagement/PredefinedCategoriesAPI/Methods/import-categories-pre-validation.md
pages/Documents/DeveloperTools/LivePersonFunctions/Foundations/liveperson-functions-cli.md

Proactively fixed the issues called out in #1698, including some improvements.

Added [log] metrics and command (and made some small corrections)

---

css/default.css
js/additionalscripts.js

Revised TOC styling

---

css/inner-page.css

hyphens: auto for h3

---

css/default.css

deleted flex from h3 and h4

---

pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/4.9.0.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/4.9.1.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/5.7.1.md

fixed tenses in 3 instances for this text: 4.9.0, 4.9.1, 5.7.1 & tested locally.
@j9t please approve

 fixed tenses in 3 instances for this text: 4.9.0, 4.9.1, 5.7.1

---

README.md

docs: add shortcuts ref

---

pages/Documents/MessagingChannels/ProactiveMessaging/changelog.md

fixed titles

---

pages/Documents/ConversationalAI/ConversationOrchestrator/api-authorization.md

This resolves https://github.com/LivePersonInc/developer-center/issues/1863

Conversation Orchestrator - Update the API Authorization docs to use the newer URLs

---

css/default.css
css/inner-page.css
js/additionalscripts.js
pages/Documents/APIGuidelines/messaging-features-capabilities-comparison.md

fixed search style and input

---

_data/documentsupdated.yaml
pages/Documents/GettingStarted/customizing-the-conversational-cloud.md

'added the content from do more with the conversational cloud to the customizing the conversational cloud page and merged the intro into one'
'added redirect from do more with the conversational cloud page'

Merge cc getting started

---

assets/schema/Welcome.json
pages/index.md

homepage link

---

README.md
pages/Documents/MessagingChannels/ConnectToMessaging/api.md
pages/Documents/MessagingChannels/ProactiveMessaging/api.md

Edited README, tweaked C2M/API docs

---

.platform.app.yaml

feat: add security-related headers (needs testing)

---

pages/Documents/DeveloperTools/LivePersonFunctions/examples.md

In addition to fixing the code issue to make the snippet "plug" and "go. Some explaining comments are added to the most "critical" sections.

:bug: Fixed a coding mistake in cache example code

---

README.md

(For branding purposes, consistent with the [Knowledge Center README](https://github.com/LivePersonInc/knowledge-center))

feat: add LivePerson logo

---

pages/Documents/GettingStarted/liveperson-apis-and-sdks.md

docs: add reference to “Model Tester External APIs,” add metadata

---

_data/documentsupdated.yaml
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/supportability.md

@j9t  @itay1313 
Please help us merge this pull request

Add document about new Android version supportability from MobileSDK team

---

feed.xml

fix: make feed valid, sort by publishing date (with fallback), reformat and clean up

---

_config.yml
feed.xml

fix: sort by page name to filter out documents without a title; extend number of items; make description content HTML; add base URL (TBC)

---

pages/Documents/ConversationalAI/CommonSolutions/set-consumer-expectations-about-wait-times-for-agents.md
pages/Documents/ConversationalAI/ConversationAssist/RecommendationSources/setting-up-bots.md
pages/Documents/ConversationalAI/ConversationAssist/agent-experience.md
pages/Documents/ConversationalAI/ConversationOrchestrator/overview.md
pages/Documents/ConversationalAI/IntentManager/best-practices.md
pages/Documents/ConversationalAI/Tutorials&Guides/UsingConversationAssist/configure-conversation-assist.md
pages/Documents/ConversationalAI/get-started-with-automation.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/supportability.md
pages/Documents/Reporting/OutboundReportingAPI/overview.md

docs: add release/update dates (and make minor formatting corrections)

---

assets/code-examples/WebAppSDK/chatStartingPageWidget/README.md
pages/Documents/Reporting/MessagingOperationsAPI/Methods/messaging-conversation.md
pages/Documents/Reporting/OperationalRealtimeAPI/Methods/agent-activity.md
pages/Documents/RichMessaging/MobileSDKandWebTemplates/multiple-checklist-template.md
pages/Documents/Security&Authentication/ConsumerAuthentication/configuration.md

fix: fix typos

---

google0411e33288466f3c.html

feat: add Google Search Console verification file

---

.platform/routes.yaml

fix: remove apparently invalid redirect

---

.platform/routes.yaml

refactor: remove superfluous rule, add alternatives to catch code example URLs

---

.platform/routes.yaml

refactor: remove rule that didn’t work previously :)

---

README.md
_layouts/default.html
feed.xml
pages/Documents/APIsandSDKs/overview.md
pages/Documents/ConversationalAI/CommonSolutions/set-consumer-expectations-about-wait-times-for-agents.md
pages/Documents/ConversationalAI/get-started-with-automation.md
pages/Documents/GettingStarted/customizing-the-conversational-cloud.md
pages/Documents/GettingStarted/getting-started-with-your-free-trial-account.md
pages/Documents/MessagingChannels/MobileAppMessagingSDKforAndroid/ReleaseNotes/supportability.md
pages/Documents/Reporting/OutboundConfigurationAPI/overview.md

refactor: switch to `date_updated`

---

_data/documentsupdated.yaml

fix DX-174

---

_data/documentsupdated.yaml

Reverts LivePersonInc/developer-center#2012

Revert "fix DX-174"

---

_includes/head.html
_layouts/default.html

Webpage Performance Test suggestions

---

README.md

docs: clarify consistency

---

Gemfile
Gemfile.lock

solved build and error on local

---

_config.yml
_includes/sidebar.html
js/additionalscripts.js
pages/Documents/APIsandSDKs/all-documents.md

removed navlink jquery function

---

_config.yml
css/color-rules.css
css/default.css
css/inner-page.css
css/syntax.css

fixed highligher rouge

---

css/syntax.css

html codeblock bug

---

Gemfile
Gemfile.lock

Reverts LivePersonInc/developer-center#2025

Revert "solved build and error on local"

---

pages/Documents/GettingStarted/getting-started-with-your-free-trial-account.md

fixed modal bug

---

pages/Documents/ConversationalAI/IntentManager/ExternalAPIs/getting-started.md
pages/Documents/MessagingChannels/ConnectToMessaging/api.md

Improved Connect To Messaging API doc

---

js/additionalscripts.js

fixed sidebar to show only if more than one item

---

js/additionalscripts.js

fixed center bug

---

pages/Documents/WebsiteMonitoring/VisitInformationAPI/overview.md
pages/Documents/WebsiteMonitoring/VisitInformationAPI/visit-information.md

refactor: edit and reformat Visit Information API docs

---

README.md

docs: add migration note

---

.github/workflows/main.yaml

fix: try fix for action issue

---

css/default.css

(Note: Arbitrary breakpoint, and this may generally need further fine-tuning.)

fix: give main content more space (show TOC later)

---

pages/Documents/APIsandSDKs/overview.md
pages/Documents/ConversationalAI/LPMessagingSDK/overview.md
pages/Documents/ConversationalAI/MessagingAgentSDK/overview.md

- new sdk entry & pages for lp-messaging-sdk
- deprecated messages for node-agent-sdk

initial lp-messaging-sdk documentation

---

README.md

docs: update notice
