- pages/documents/data/data-access/overview.md
The DA API and its keys are not (yet) self-served through LiveEngage.
> Update how to obtain API keys for the Data Access API

- pages/documents/data/messaging-interactions/methods/conversations.md
- pages/documents/data/messaging-interactions/methods/get-conversation-by-conversation-id.md
- pages/documents/data/messaging-interactions/methods/get-conversations-by-consumer-id.md
Updated the markdown for <domain> in the messaging interactions api documentation to be {domain}, that way it will display.
> Fixed domain not displaying in Messaging Interactions API documentation

- pages/documents/guides/StructuredContent/overview.md
Corrected some examples, as well as the expected Type for coordinate values (I have used Float values with success). It may be that there is some type conversion going on behind the scenes and Floats are converted to Strings or vice versa. Should probably confirm with UMS product and update docs again accordingly.
> Example Corrections

- pages/documents/guides/Authentication/DetailedAPI.md
According to the [Web Messaging Configuration Guide](https://s3-eu-west-1.amazonaws.com/ce-sr/CA/Messaging/Web+Messaging+Configuration+Guide+v1.0.pdf) the customerId must be set.
I've confirmed this on my account, and without the customerId set, no messaging is offered to the visitor.
> set engagement attribute customerId for Web Messaging

- pages/documents/consumer experience/server-chat/Methods/start-chat.md
Specifically mention "request" key in the Body Parameters description
> Fix Start chat body parameters description

- pages/documents/AgentExperienceAndBots/ChatAgentAPI/Methods/accept-chat.md
*Reference case#00787574 - Chat Agent API bot going to away*
If an assigned chat is not accepted within 20 seconds, the system decides the agent must be idle and changes the agent state to 'away'.
In a scenario where a chat-bot is using the Chat Agent API, it should periodically check for it availability state and, if not intentionally away, set the status back to 'online'.
Should this also be added to the general [Retry and KeepAlive Best Practices](/retry-and-keepalive-best-practices-overview.html) and/or to a new page "Best Practices And Troubleshooting" within the Chat Agent API tree?
> Bot agent state set to away by system

- pages/documents/ClientSideConfiguration/JavaScriptChatSDK/Methods/startchatrequestchat.md
This document contains several parameters that would only work on Legacy accounts. Should we be including those in our public documentation at this point?
> Remove Legacy only parameters

- pages/documents/AgentExperienceAndBots/BotConnectors/CustomThirdPartyBot.md
There is a link to the Messaging Agent SDK that is not rendering correctly.
This is a fix for #313.
> GH-313: Fixed link on Custom Third Party Bot Page

- pages/documents/DeveloperTools/FaaS/Developing/toolbelt.md
The secret client returns Promises rather than already resolved Objects. This can be seen in the example code but is not properly reflected in the tables.
> :pencil: Corrected misleading return types

- css/register.css
Styling changes requested by Greg Fyke and James Poulin -- this branch can be pulled down and built locally with changes viewable at `/register.html`. 
I notice that select options don't completely align with the select element in chrome: this is a pre-existing issue that should be addressed separately, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#Styling_with_CSS for details on potential mitigations/alternatives.
> add formWrapper bottom margin, reduce input font-size and padding

- pages/documents/DeveloperTools/FaaS/Developing/toolbelt.md
Whitelisting api.liveperson.net is not needed anymore.
> FS-291: Whitelisting api.liveperson.net

- pages/documents/MessagingChannels/MobileAppMessagingSDKforAndroid/VoiceandVideoforAndroidSDK/Changelog.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforAndroid/VoiceandVideoforAndroidSDK/Customizing.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforAndroid/VoiceandVideoforAndroidSDK/FAQ.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforAndroid/VoiceandVideoforAndroidSDK/GettingStarted.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforAndroid/VoiceandVideoforAndroidSDK/Introduction.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforAndroid/VoiceandVideoforAndroidSDK/Sample-Apps.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforAndroid/VoiceandVideoforAndroidSDK/liveengageConfiguration.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/VoiceandVideoforiOSSDK/Changelog.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/VoiceandVideoforiOSSDK/Customizing.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/VoiceandVideoforiOSSDK/GettingStarted.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/VoiceandVideoforiOSSDK/Introduction.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/VoiceandVideoforiOSSDK/LiveEngageConfiguration.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/VoiceandVideoforiOSSDK/Sample-Apps.md
- pages/documents/MessagingChannels/MobileAppMessagingSDKforiOS/VoiceandVideoforiOSSDK/appendix.md
CoApp is deprecated, and we need to add a deprecation notice to the developer docs.
Please also remove the following pages:
- Getting Started
- Customizing
- LiveEngage Configuration
- Sample App
- Appendix
Regarding to the Readme, the maintainer has to remove the pages from the sidebar.
> Add deprecation notice

- pages/Documents/DeveloperTools/LivePersonFunctions/DevelopingwithFaaS/overview.md
This has been tested in staging. It is already merged to dev pass
> hyper link was broken on markdown file added a redirect to correct file

- package-lock.json
- package.json
This PR fixes 1 high, 2 moderate and 428 low vulnerabilities.
It was achieved by running 'npm audit fix', and updated the patch versions of **lodash** and **browser-sync**, and a minor version of **jquery**.
> Update packages - fixes 1 high, 2 moderate and 428 low vulnerabilities

- pages/Documents/Security&Authentication/ConsumerAuthentication/detailed-api.md
Confirmed with Liveperson R&D
Liveperson is working with a standard library that does everything Oauth2/openid
It only requests in application/x-www-form-urlencoded per the RFC. There is no option for JSON in the RFC.
> Content-Type is wrong

- pages/Documents/ConversationalAI/Third-PartyBots/getting-started.md
add hint to create fresh bot agents fro ThirdPartyBots, since otherwise CB and TPB will kick each other out.
> :memo: add hint to use fresh bot agents instead CB ones

- .gitignore
- README.md
Added a warning to the readme to prevent new people from going down a needless rabbit hole if they install "ruby latest." Apparently Jekyll and Ruby 3.x.x do not get along and you need to stick with 2.7.x.
Also added the lockfiles to the .gitignore.
> adding Ruby version warning, adding lock files to gitignore

- _includes/registerHead.html
- _layouts/default.html
- _layouts/documents.html
- _layouts/hidden-layout.html
- _layouts/homepage.html
- _layouts/pagenotfound.html
- _layouts/solutions.html
Changes "LiveEngage" to "the LivePerson Conversational Cloud" in the meta description in 7 base template docs.
> fixing phrasing in meta description

- pages/Documents/Reporting/MessagingOperationsAPI/Methods/messaging-estimated-wait-time.md
Deprecation note added by Stefan Seedorf (Github id: globalcrowd). The API endpoint is owned by the CUA team.
> Add deprecation notice to Messaging EWT API

- pages/Documents/ConversationalAI/ConversationAssist/RecommendationSources/configuring-settings.md
- pages/Documents/ConversationalAI/ConversationAssist/RecommendationSources/setting-up-bots.md
- pages/Documents/ConversationalAI/ConversationAssist/RecommendationSources/setting-up-knowledge-bases.md
- pages/Documents/ConversationalAI/ConversationAssist/agent-experience.md
- pages/Documents/ConversationalAI/ConversationAssist/faqs.md
- pages/Documents/ConversationalAI/ConversationAssist/overview.md
- pages/Documents/ConversationalAI/ConversationAssist/reports.md
- pages/Documents/ConversationalAI/ConversationAssist/testing.md
- pages/Documents/ConversationalAI/ConversationAssist/troubleshooting.md
Misc. copyedits include replacing "here" links with other link labels and adding alt text to images within the Conversation Assist section of docs.
> Update number of hours that recommendations are cached and other misc. copyedits

- pages/Documents/Security&Authentication/CookiesandConversationalCloud/overview.md
Add lpTestCookie information to 'Security and Authentication' -> 'Cookies and Conversational Cloud' -> 'Overview'. This cookie is used only for testing whether the browser supports cookies, where 'timestamp' equals the current time (represented in milliseconds since the ECMAScript epoch).
> Add lpTestCookie cookie to 'Cookies and Conversational Cloud' overview page

- pages/Documents/Security&Authentication/ConsumerAuthentication/detailed-api.md
base64-encoded and base64url-encoded are different, we require the latter, and this error in the document has enraged our client RBC
> Key should be base64url encoded rather than base64

- pages/Documents/Security&Authentication/ConsumerAuthentication/detailed-api.md
clarifying that JWKS should return pubkey modulus in base64url encoding
> further refinement to base64 encoding requirement

- pages/Documents/GettingStarted/getting-started-with-your-free-trial-account.md
Removed traces of "free trial" from the article as requested and re-worded according to the demo landing page.
> reworded free trial link to reflect demo as requested
